### ISSUE TITLE
Q: ccid plugin?

### ISSUE THREAD

**Issue by Kreyren** [fbegyn/nixos-configuration#17]
Hey, i am trying to make web eID work on my end and using your repo as a reference.

Can you elaborate on why is the `ccid` needed here?

https://github.com/fbegyn/nixos-configuration/blob/8ba0191d2cfa5154b62d835820fb3f7ea44d7446/common/eid.nix#L12

Thanks! <3

**Comment by fbegyn** [comment]
It could be that it works without `ccid`, but this package provides a generic driver for smartcard readers and makes it available in the environment for `pcscd`. If you have other drivers available, you might not need it.

I also have to admit this was in turn taken from https://github.com/chvp/nixos-config/blob/main/modules/programs/eid/default.nix
